In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'2.2.2'

In [4]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [5]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


In [34]:
df.describe().round(2)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
count              9704.00        9222.00     9704.00         9704.00   
mean                199.71           3.96      149.83         3001.28   
std                  49.46           2.00       28.78          497.89   
min                  10.00           0.00       37.00          952.68   
25%                 170.00           3.00      131.00         2666.25   
50%                 200.00           4.00      152.00         2993.23   
75%                 230.00           5.00      168.00         3334.96   
max                 380.00          13.00      271.00         4739.08   

       acceleration  model_year  num_doors  fuel_efficiency_mpg  
count       8774.00     9704.00    9202.00              9704.00  
mean          15.02     2011.48      -0.01                14.99  
std            2.51        6.66       1.05                 2.56  
min            6.00     2000.00      -4.00                 6.20  
25%           13.30     2006.00      -1.00                13.27  
50%           15.00     2012.00       0.00                15.01  
75%           16.70     2017.00       1.00                16.71  
max           24.30     2023.00       4.00                25.97

In [7]:
fuel_type = df['fuel_type'].value_counts()

In [8]:
fuel_type

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

In [9]:
fuel_efficiency_mpg = df['fuel_efficiency_mpg'].value_counts()

In [10]:
fuel_efficiency_mpg

fuel_efficiency_mpg
14.884467    1
13.231729    1
13.688217    1
14.246341    1
16.912736    1
            ..
16.175820    1
20.504447    1
13.386605    1
12.298355    1
16.823554    1
Name: count, Length: 9704, dtype: int64

In [11]:
df['horsepower']

0       159.0
1        97.0
2        78.0
3         NaN
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

# Handling missing values

In [12]:
median_value = df['horsepower'].median()
median_value

np.float64(149.0)

In [13]:
freq_value = df['horsepower'].mode()
freq_value

0    152.0
Name: horsepower, dtype: float64

In [14]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])
df['horsepower']

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [15]:
median_value = df['horsepower'].median()
median_value

np.float64(152.0)

In [16]:
df['origin']

0       Europe
1          USA
2       Europe
3          USA
4       Europe
         ...  
9699    Europe
9700       USA
9701       USA
9702       USA
9703      Asia
Name: origin, Length: 9704, dtype: object

In [17]:
car_origin = df['origin']
car_origin

0       Europe
1          USA
2       Europe
3          USA
4       Europe
         ...  
9699    Europe
9700       USA
9701       USA
9702       USA
9703      Asia
Name: origin, Length: 9704, dtype: object

# Values of cars from Asia only

In [18]:
asian_cars = df[df['origin'] == 'Asia']
asian_cars

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0       152.0     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

# Max. fuel efficiency for Asian cars

In [19]:

max_fuel_eff = asian_cars['fuel_efficiency_mpg'].max()
max_fuel_eff

np.float64(23.759122836520497)

In [20]:
selected_cols = asian_cars[['vehicle_weight', 'model_year']]
selected_cols

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

# First seven values from the selected columns 

In [21]:
first_sev_values = selected_cols.head(7)
first_sev_values

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

# Getting The Numpy Array

In [22]:
X = first_sev_values.to_numpy()

In [23]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [24]:
X_transpose = X.T 
X_transpose

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

# Getting the dot product of the matrix transpose(X.T) and the original matrix(X) 

In [25]:
XTX = X.T @ X
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [26]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [27]:
# y arrays
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [31]:
w = (XTX_inv @ X.T) @ y

# Sum of all elements

In [32]:
sum_w = np.sum(w)
sum_w

np.float64(0.5187709081074016)